# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def shared_pods
	 pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :submodules => true	
	pod 'RealmLoginKit'
end

target 'RealmDraw iOS' do
	use_frameworks!
	shared_pods
end

target 'RealmDrawTests' do
	use_frameworks!
	shared_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end